name: Cordova Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Cordova CLI
      run: npm install -g cordova

    - name: Install project dependencies
      run: npm install

    - name: Add Android platform (if missing)
      run: |
        if [ ! -d "platforms/android" ]; then
          cordova platform add android
        fi

    - name: Build Cordova Android App
      run: cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cordova-debug-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk